### ISSUE TITLE
Plugin stopped working after sensu-plugins was updated to 1.3.0

### ISSUE THREAD

**Issue by mnellemann** [sensu-plugins/sensu-plugins-opsgenie#14]
Hey,

Looks like my Puppet sensu module decided to update the `sensu-plugins` gem to 1.3.0 (always using latest version I guess). This breaks the opsgenie-handler plugin (and alot of other plugins ... ).

Could you release a version that works w. the updated `sensu-plugins` gem ?

`{"timestamp":"2016-06-14T07:06:52.609481+0200","level":"info","message":"handler output","handler":{"command":"handler-opsgenie.rb","type":"pipe","filters":[],"severities":["ok","warning","critical","unknown"],"name":"opsgenie"},"output":["/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in`to_specs': Could not find 'sensu-plugin' (= 1.2.0) - did find: [sensu-plugin-1.3.0](Gem::MissingSpecVersionError)\nChecked in 'GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.3.0:/opt/sensu/.gem/ruby/2.3.0', execute `gem env` for more information\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in`each'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in`activate'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `block in activate_bin_path'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in`synchronize'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `activate_bin_path'\n\tfrom /opt/sensu/embedded/bin/handler-opsgenie.rb:22:in`<main>'\n"]}
`

**Comment by eheydrick** [comment]
Hi @mnellemann, version 2.0.0 of the plugin was just released with the `sensu-plugin` dependency changed to `~> 1.2` and thus will work with `sensu-plugin` 1.3.0.
