### ISSUE TITLE
Recipients should come from client not from server config

### ISSUE THREAD

**Issue by jaxxstorm** [sensu-plugins/sensu-plugins-opsgenie#3]
Setting the recipient on the server side means that flexible alerting isn't possible. The handler should check for the present of client['teams'] or client['recipient'] and then fall back to the handler config if it's not found.

This would be a custom sensu tag, so we should update the docs to make this known.

**Comment by eheydrick** [comment]
This would be a nice improvement. Would happily take a PR for this functionality. See also PR https://github.com/sensu-plugins/sensu-plugins-opsgenie/pull/5 which lets you override opsgenie settings in the check.

**Comment by analytically** [comment]
Hi, I've released 0.0.3, which allows the check to override the config. Can you try with that version?

**Comment by eheydrick** [comment]
Reopen if this is still an issue.
